travis:
  secure:
    BINSTAR_TOKEN: oSVzE43pkxOik/NqGg2OjfRVr9KSk4wSqOe/CQk9ctABcnMMj49fW0477lbha5aSfQdynr/o5JLpaOphW2yPc+Ti7u4uM2fC7Y5/gGDiZOx1WRN6hd/cN10WN1L7170PgQB3CLrIZegn7TsKSBlbRdcmxgNc8Uoawb2wgyxn3kPnrPZ38Sy47Olhdp+MuBaOpPri51YPgyA4ugZk0to2yydsuiM/KHLucaKr1kcOJxj6k0ps3tnD3R87PInZB4UozmprTL3/psYNd0OW6bI/Jpba2UEKH8nzmnxYMIo62cxa+jadkJC387zZOUYyZuwGHHVUCqdoC/gzPAZmGfsS9P1D46httr8W2nkwfebu6xSK1pxImXewkSzHh7K5GZ/tabOMMh9reSthJLcTn0I1vn7VpDUot5NVB9fnL6E1j+I6xK+ZzwEKVoIxlmNwmXZ5HQGvg0TnSJFS32GqiNhBpcg1hlWkcsrGQTrlCeFxBq7mNgwfOdyEs4o6vgYgH3bKeVGt/9+IaECihyH2Fq7yQnuJqrjuobT6l2ZZYQdu9/szKnJ3GKbk3LpZhAJPTJ6PVrJ6ZAysIwRls36Q+2EmItmI1oWWaH6+rBfW3iaWM/vaB3+EDy95Zlcbkwq8AZK0nPMSzYuJQeiVp6JK1HyCyRQfyQvkvwa9+GiBsfGa+LM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
